[general]
static=yes
writeprotect=no
clearglobalvars=no

[default]
exten => _.,1,Answer()
same => n,Wait(1)
same => SpeechCreate(myengine)
same => SpeechStart()
same => n, SpeechBackground(silence/1, 5)
same => n,Verbose(1, Recognized: ${SPEECH_TEXT(0)} with confidence ${SPEECH_SCORE(0)})
same => n,Set(stt_result=${SPEECH_TEXT(0)})
same => n,SpeechDestroy()
same => n,AGI(agi://127.0.0.1:8080/agi)
same => n,Hangup()